name: CD 

on: 
  workflow_dispatch:
    
jobs:
  build: 
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v3 
      - uses: actions/setup-node@v3
        with:
          node-version: 16 
          cache: 'npm'
          cache-dependency-path: hangman-front/package-lock.json 
      - name: build 
        working-directory: ./hangman-front
        run: |
          npm ci 
          npm run build --if-present
      - uses: actions/upload-artifact@v3 
        with:
          name: build-code
          path: hangman-front/dist/

  delivery:
    runs-on: ubuntu-latest
    needs: build 

    steps:
      - uses: actions/checkout@v3 
      - uses: actions/download-artifact@v3 
        with:
          name: build-code 
          path: hangman-front/dist/
          
      - name: Build and Push Docker Image 
        working-directory: ./hangman-front
        env:
          DOCKER_USER: "josepmariatuset"
          DOCKER_REPOSITORY: "hangman-front"
        run: |
          echo "${{ secrets.GIT_DOCKER_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          image=ghcr.io/$DOCKER_USER/$DOCKER_REPOSITORY
          image=$(echo $image | tr '[A-Z]' '[a-z]')
          version=$(echo ${{ github.ref }})
          version=$(date +%s)
          version=$(echo $version | sed -e 's,.*/\(.*\),\1,')

          docker build . --file Dockerfile.workflow --tag $image:$version 
          docker images
          docker push $image:$version 
