name: CD 

on: 
  workflow_dispatch:
    
jobs:
  build: 
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3 
      - uses: actions/setup-node@v3
        with:
          node-version: 16 
          cache: 'npm'
          cache-dependency-path: hangman-front/package-lock.json 
      - name: build 
        working-directory: ./hangman-front
        run: |
          npm ci 
          npm run build --if-present
      - uses: actions/upload-artifact@v3 
        with:
          name: build-code
          path: hangman-front/dist/

  delivery:
    runs-on: ubuntu-latest
    needs: build 

    steps:
      - uses: actions/checkout@v3 
      - uses: actions/download-artifact@v3 
        with:
          name: build-code 
          path: hangman-front/dist/
          
      - name: Build and Push Docker Image 
        working-directory: ./hangman-front
        env:
          DOCKER_USER: "jmtuset"
          DOCKER_REPOSITORY: "hangman-front"
#          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          image=$DOCKER_USER/$DOCKER_REPOSITORY:$(date +%s)
          docker build . --file Dockerfile.workflow --tag $image 

# docker push $image
